List adalah struktur data serbaguna, terurut, dan mutable yang digunakan untuk menyimpan kumpulan item dalam satu variabel.

In [41]:
arr = [1, 2, 3, 4, 5]

print(arr[0], arr[4])

1 5


Pada baris pertama, berfungsi membuat sebuah list yang diberi nama "arr".
List tersebut berisi beberapa angka yaitu 1, 2, 3, 4, dan 5.

Di Python, list itu punya indeks yang dimulai dari 0, bukan dari 1.
Jadi posisi datanya seperti ini:
indeks = list
arr[0] = 1
arr[1] = 2
arr[2] = 3
arr[3] = 4
arr[4] = 5

Pada baris kedua Perintah ini digunakan untuk mencetak isi list pada indeks ke-0 dan indeks ke-4.
arr[0] berarti mencetak angka pertama yaitu 1.
arr[4] berarti mencetak angka terakhir yaitu 5.

Jadi output yang dihasilkan adalah:
1 5

In [42]:
print(len(arr))

5


Pada kode diatas digunakan fungsi "len()" untuk menghitung jumlah data yang ada di dalam list arr.

Fungsi len di Python berfungsi untuk mengetahui berapa banyak elemen yang ada di dalam suatu list, string, atau variabel yang memiliki banyak isi.
Artinya program akan menghitung jumlah isi list arr, kemudian hasilnya akan dicetak.
bisa dilihat dari list arr terdapat angka 1, 2, 3, 4, 5 yang berarti terdapat 5 angka maka outputnya:
5

In [43]:
names = [ "Dave", "Mark", "Ann" ]
# Membuat list bernama names yang berisi 3 data string yaitu Dave, Mark, dan Ann

names.append("Jeff")
# append digunakan untuk menambahkan data ke dalam list
# "Jeff" ditambahkan ke posisi paling akhir dari list names
print(names)
# mencetak isi list names setelah ditambahkan data baru

['Dave', 'Mark', 'Ann', 'Jeff']


In [44]:
names.insert(2, "Sydney")
print(names)

['Dave', 'Mark', 'Sydney', 'Ann', 'Jeff']


insert digunakan untuk menambahkan data pada posisi tertentu, seperti Sydney yang akan ditambahkan tetapi bukan diletakkan pada indeks terakhir tetapi diletakkan pada indeks ke-2, jadi angka 2 adalah indeks tempat data akan dimasukkan.

In [45]:
c = names[0:2] 
print(c)

['Dave', 'Mark']


Code pada baris pertama digunakan untuk mengambil sebagian isi list dari indeks 0 sampai sebelum indeks 2.
Indeks sebelum simbol : merupakan indeks awal yang akan diambil, sedangkan indeks setelah simbol : adalah batas akhir pengambilan, tetapi indeks tersebut tidak ikut diambil.
contoh:
indeks 0 = Dave
indeks 1 = Mark
indeks 2 = Sydney (tidak ikut karena batasnya 2)
maka outputnya:
['Dave', 'Mark']

In [46]:
e = names[2:]
print(e) 

['Sydney', 'Ann', 'Jeff']


Code tersebut digunakan untuk mengambil sebagian isi list mulai dari indeks ke-2 sampai indeks terakhir.
Jika setelah tanda : tidak ditulis angka, maka data akan diambil sampai akhir list.

In [47]:
d = names[:3]
print(d)

['Dave', 'Mark', 'Sydney']


Code tersebut digunakan untuk mengambil sebagian isi list dari indeks awal sampai sebelum indeks ke-3.
Jika sebelum tanda : tidak ditulis angka, maka pengambilan dimulai dari indeks 0.

In [48]:
a = [1, 2, 3] + [4, 5] 
print(a)

[1, 2, 3, 4, 5]


Code pada baris pertama digunakan untuk menggabungkan dua buah list menjadi satu list.
List [1, 2, 3] digabung dengan list [4, 5] menggunakan tanda +, sehingga menghasilkan list baru yang berisi semua elemen dari kedua list tersebut.
Perintah print(a) digunakan untuk menampilkan hasil penggabungan list.

In [49]:
b = [1, "Dave", 3.14, ["Mark", 7, 9, [100, 101]], 10]
print(b[1])

Dave


Pada baris pertama berfungsi membuat list bernama b yang berisi beberapa tipe data, ada integer, string, float, dan juga list di dalam list (nested list)
pada baris kedua mengambil data pada indeks ke-1 dari list b.
indeks dimulai dari 0, jadi indeks ke-1 adalah elemen kedua.
contoh: 
Indeks 0 = 1
Indeks 1 = "Dave"
Indeks 2 = 3.14
Indeks 3 = ["Mark", 7, 9, [100, 101]]
Indeks 4 = 10

karena diambil b[1]
maka outputnya:
Dave

In [50]:
print(b[3][2]) 

9


Code tersebut digunakan untuk mengambil data dari list di dalam list.
b[3] mengambil elemen ke-3 yang berupa list, kemudian [2] mengambil elemen ke-2 dari list tersebut.

isi list sebelumnya:
indeks list b:
0 = 1
1 = "Dave"
2 = 3.14
3 = ["Mark", 7, 9, [100, 101]]
4 = 10

isi dari indeks ke-3:
["Mark", 7, 9, [100, 101]]
maka b[3][2] Artinya:
ambil list di indeks 3.
lalu ambil indeks 2 dari list indeks 3.
Nilai pada indeks tersebut adalah 9, sehingga output yang ditampilkan adalah 9.

In [51]:
print(b[3][3][1])

101


Code tersebut digunakan untuk mengambil data dari list di dalam list.
b[3] mengambil elemen ke-3 yang berupa list, kemudian [3] mengambil elemen ke-3 dari list tersebut, lalu [1] mengambil elemen ke-1 dari list di dalamnya.

isi list sebelumnya:
indeks list b:
0 = 1
1 = "Dave"
2 = 3.14
3 = ["Mark", 7, 9, [100, 101]]
4 = 10

isi dari indeks ke-3:
["Mark", 7, 9, [100, 101]]

di dalam indeks ke-3 terdapat list lagi:
[100, 101]

maka b[3][3][1] artinya:
ambil list di indeks 3.
lalu ambil indeks 3 dari list indeks 3.
kemudian ambil indeks 1 dari list tersebut.

Nilai pada indeks tersebut adalah 101, sehingga output yang ditampilkan adalah 101.

Tuple adalah struktur data untuk menyimpan kumpulan elemen yang terurut dan tidak dapat diubah setelah dibuat.

In [52]:
a = (1, 4, 5, -9, 10)
person = ("John", "Doe", 21554221)

print(a)
print(person)

(1, 4, 5, -9, 10)
('John', 'Doe', 21554221)


Code tersebut digunakan untuk membuat tuple dan menampilkan isi tuple.
Tuple adalah tipe data yang hampir sama dengan list, tetapi tidak bisa diubah, dan menggunakan tanda kurung biasa ( ).
isi dari tuple a = (1, 4, 5, -9, 10)
isi dari tuple person = ("John", "Doe", 21554221)
print(a) artinya menampilkan semua isi tuple a.
print(person) artinya menampilkan semua isi tuple person.
karena tidak menggunakan indeks, maka semua elemen dalam tuple akan dicetak.
Output yang dihasilkan adalah:
(1, 4, 5, -9, 10)
('John', 'Doe', 21554221)

In [53]:
print(a[0]) 
print(a[2])  

1
5


Code tersebut digunakan untuk mengambil data dari tuple berdasarkan indeks.
Tuple menggunakan indeks yang dimulai dari 0, sama seperti list.
isi indeks tuple a:
0 = 1
1 = 4
2 = 5
3 = -9
4 = 10
print(a[0]) artinya mengambil elemen pada indeks ke-0 yaitu 1.
print(a[2]) artinya mengambil elemen pada indeks ke-2 yaitu 5.
maka outputnya:
1
5

In [54]:
a[0] = 2 

TypeError: 'tuple' object does not support item assignment

Code tersebut digunakan untuk mencoba mengubah isi tuple, tetapi akan menyebabkan error, karena tuple tidak bisa diubah.
a[0] = 2 artinya code tersebut mencoba mengubah nilai pada indeks ke-0 dari tuple a menjadi 2.
karena itu, perintah tersebut akan menghasilkan error.

In [ ]:
# code yang mengubah nilai indeks tuple yang benar
a = (1, 4, 5, -9, 10)

a = list(a)   # tuple diubah jadi list supaya bisa diubah
a[0] = 2      # mengganti nilai indeks ke-0
a = tuple(a)  # dijadikan tuple lagi

print(a)

(2, 4, 5, -9, 10)


Set adalah tipe data koleksi yang tidak berurutan (unordered), tidak terindeks, dan hanya menyimpan elemen unik (otomatis menghapus duplikat). Set sangat berguna untuk operasi himpunan seperti irisan, gabungan, dan selisih. Dibuat menggunakan kurung kurawal {} atau fungsi set(), set bersifat mutable (elemen bisa ditambah/dihapus).

In [ ]:
s = set([3, 4, 9, 10])  
t = set("Hello")        

print(s) 
print(t) 

{9, 10, 3, 4}
{'l', 'e', 'H', 'o'}


Code tersebut digunakan untuk membuat set dan menampilkan isi set.
s = set([3, 4, 9, 10]) artinya membuat set bernama s dari list yang berisi angka 3, 4, 9, dan 10 karena Set tidak memiliki urutan tetap, jadi hasilnya bisa berubah posisi.
t = set("Hello") artinya membuat set dari string "Hello". Set akan mengambil setiap huruf dan menghapus huruf yang sama, seperti Huruf l terdapat dua, tetapi di set hanya akan mencetak satu karena set tidak boleh ada duplikat.

In [ ]:
print(s[0])

TypeError: 'set' object is not subscriptable

Code tersebut digunakan untuk mencoba mengambil elemen dari set menggunakan indeks, tetapi akan menyebabkan error, karena set tidak memiliki indeks seperti list atau tuple. 
Pada code sebelumnya, s adalah set yang dibuat dari angka 3, 4, 9, dan 10. Seperti yang sebelumnya dikatakan diatas set merupakan tipe data yang tidak berurutan, sehingga setiap elemen tidak memiliki posisi tetap dan tidak bisa diakses menggunakan indeks.
Pada baris print(s[0]), code tersebut mencoba mengambil elemen pada indeks ke-0 dari set s. Namun set tidak mendukung penggunaan indeks, sehingga perintah tersebut tidak bisa dilakukan.

In [ ]:
s = set([3, 4, 9, 10])

for x in s:
    print(x)

9
10
3
4


Code tersebut digunakan untuk menampilkan isi set dengan menggunakan perulangan, pada code for x in s:, perintah tersebut digunakan untuk mengambil setiap elemen yang ada di dalam set s satu per satu. Setiap elemen yang diambil akan disimpan sementara ke dalam variabel x.
Kemudian pada baris print(x), nilai yang sedang berada di dalam variabel x akan ditampilkan ke layar. Karena perulangan berjalan sampai semua elemen di dalam set habis, maka semua isi set akan ditampilkan satu per satu.
Hasil yang ditampilkan bisa berbeda urutan setiap kali dijalankan, karena set tidak memiliki urutan tetap.

In [ ]:
contoh_set1 = {12, 13, 14, 15} # membuat set bernama contoh_set1 yang berisi angka 12, 13, 14, dan 15
contoh_set2 = {14, 15, 16, 17} # membuat set bernama contoh_set2 yang berisi angka 14, 15, 16, dan 17

print("set 1 =", contoh_set1) # menampilkan tulisan "set 1 =" lalu menampilkan isi dari contoh_set1
print("set 2 =", contoh_set2) # menampilkan tulisan "set 2 =" lalu menampilkan isi dari contoh_set2

set 1 = {12, 13, 14, 15}
set 2 = {16, 17, 14, 15}


Karena set bersifat tidak berurutan (unordered) maka output yag dihasilkan akan berbeda-beda atau urutannya acak.

In [ ]:
union = contoh_set1 | contoh_set2
print(union)

{12, 13, 14, 15, 16, 17}


pada baris pertama tanda | digunakan untuk operasi union pada set, union artinya menggabungkan dua set menjadi satu, semua elemen dari contoh_set1 dan contoh_set2 digabung dan jika ada angka yang sama, hanya ditulis satu kali.
output yang dihasilkan adalah {12, 13, 14, 15, 16, 17}
angka 14 dan 15 tidak ditulis dua kali karena set tidak boleh duplikat dan urutan bisa berbeda karena set tidak berurutan.

In [ ]:
intersection = contoh_set1 & contoh_set2
print(intersection)

{14, 15}


Pada baris pertama tanda & digunakan untuk operasi intersection pada set, intersection artinya mencari elemen yang sama dari kedua set dan hanya angka yang ada di contoh_set1 dan contoh_set2 yang akan diambil
output yang dihasilkan {14, 15} karena hanya angka itu yang terdapat di kedua set.

In [ ]:
difference = contoh_set1 - contoh_set2
print(difference)

{12, 13}


pada baris pertama tanda - yang ada diantara contoh_set1 dan contoh_set2 digunakan untuk operasi difference pada set, difference artinya mencari elemen yang hanya ada di contoh_set1 dan tidak ada di contoh_set2.
Maka outputnya 12 dan 13 yang hanya ada di contoh_set1 sedangkan 14 dan 15 tidak ikut karena ada di kedua set.

In [ ]:
symmetric_difference = contoh_set1 ^ contoh_set2
print(symmetric_difference)

{12, 13, 16, 17}


pada baris pertama tanda ^ digunakan untuk operasi symmetric difference pada set. symmetric difference artinya mengambil elemen yang berbeda dari kedua set, elemen yang sama di kedua set tidak ikut diambil
14 dan 15 tidak ikut karena ada di kedua set, yang diambil hanya elemen yang tidak sama.
Makaq outputnya {12, 13, 16, 17}

In [ ]:
s = set([3, 4, 9, 10])
t = set("Hello")

print(s)
print(t)

{9, 10, 3, 4}
{'l', 'e', 'H', 'o'}


Pada baris pertama membuat set s dari list [3, 4, 9, 10]
Pada baris kedua membuat set t dari string "Hello"
setiap huruf akan menjadi elemen set dan jika di cetak huruf yang sama akan dihapus, jadi "l" pada "Hello" tidak akan muncul dua kali.
jadi outputnya:
{9, 10, 3, 4}
{'H', 'e', 'l', 'o'}

In [ ]:
t.add('x') 
print(t)

{'e', 'x', 'l', 'o', 'H'}


Pada add digunakan untuk menambahkan elemen ke dalam set t. Maka huruf 'x' akan ditambahkan ke set, jika elemen belum ada di set, maka akan ditambahkan tetapi jika elemen ada di dalam set tidak akan ditambahkan.
jadi outputnya {'H', 'l', 'e', 'x', 'o'}
kembali lagi urutan bisa berbeda karena set bersifat tidak berurutan.

In [ ]:
s.update([10, 37, 42]) 
# update digunakan untuk menambahkan beberapa elemen ke dalam set s
# data yang ditambahkan berasal dari list [10, 37, 42]
# jika ada elemen yang sudah ada di set, maka tidak akan ditambahkan lagi
print(s)
# menampilkan isi set s setelah ditambahkan elemen
# urutan bisa berbeda karena set bersifat tidak berurutan.

{3, 4, 37, 9, 10, 42}


In [ ]:
t.remove('H')
# remove digunakan untuk menghapus elemen dari set t
# elemen 'H' akan dihapus dari set
# jika elemen ada, maka akan berhasil dihapus
# jika elemen tidak ada, akan muncul error
print(t)
# menampilkan isi set t setelah elemen 'H' dihapus
# urutan bisa berbeda karena set bersifat tidak berurutan.

{'e', 'x', 'l', 'o'}


In [ ]:
a = {
    "username": "labfti",
    "home": "/home/labfti/",
    "uid": 500
}

print(a)

{'username': 'labfti', 'home': '/home/labfti/', 'uid': 500}


a adalah dictionary. Dictionary tersebut memiliki 3 pasangan key dan value:
"username" → "labfti"
"home" → "/home/labfti/"
"uid" → 500
print(a) digunakan untuk menampilkan isi dictionary ke layar.
Program ini membuat dictionary berisi data pengguna lalu mencetaknya ke layar.
output yang dihasilkan:
{'username': 'labfti', 'home': '/home/labfti/', 'uid': 500}

In [ ]:
u = a["username"]   
d = a["home"]      

print(u)
print(d)

labfti
/home/labfti/


Pada baris pertama artinya kita meminta program mengambil nilai dari key username pada dictionary a, lalu menyimpannya ke variabel u.
Pada baris kedua artinya kita mengambil nilai dari key home pada dictionary a, lalu menyimpannya ke variabel d.
maka outputnya:
labfti
/home/labfti/

In [ ]:
a["username"] = "pxl" # Mengubah nilai key "username" dari "labfti" menjadi "pxl"
a["home"] = "/home/pxl" # Mengubah nilai key "home" dari "/home/labfti/" menjadi "/home/pxl"
a["shell"] = "/usr/bin/bash" # Menambahkan key baru yaitu "shell" dengan nilai "/usr/bin/bash"
print(a) 

{'username': 'pxl', 'home': '/home/pxl', 'uid': 500, 'shell': '/usr/bin/bash'}


In [ ]:
print('username' in a)
#Baris kode ini digunakan untuk mengecek apakah key username ada di dalam dictionary a.
#Kata in berfungsi untuk melakukan pengecekan.
#Jika key username ada, maka outputnya True tetapi jika tidak ada, maka outputnya False.

True


soal bonus 1
apa bedanya list dan tuple?
List digunakan ketika data tersebut masih bisa diubah, misalnya jika ingin menambah, menghapus, atau mengganti data. List ditulis menggunakan tanda kurung siku [ ].
Sedangkan tuple digunakan ketika data tersebut tidak boleh diubah setelah dibuat. Jadi datanya bersifat tetap. Tuple ditulis menggunakan tanda kurung biasa ( ).
Kesimpulannya bahwa list lebih fleksibel karena datanya bisa diubah, sedangkan tuple lebih aman untuk data yang tidak ingin diubah.

soal bonus 2
sebutkan minimal 3 karakteristik set!
1.Tidak memiliki urutan (unordered), artinya data di dalam set tidak memiliki posisi atau indeks seperti list.
2.Tidak boleh ada data yang sama (unik), jadi jika ada nilai yang sama, Python hanya akan menyimpan satu saja.
3.Menggunakan tanda kurung kurawal { } saat membuat set.

In [ ]:
# Sebelum diubah
print(dict([["Nama","Chatrina"],["NIM","535250096"],["Prodi","Informatika"],["Matakuliah","Numed"]]))

{'Nama': 'Chatrina', 'NIM': '535250096', 'Prodi': 'Informatika', 'Matakuliah': 'Numed'}


soal bonus 3
konversi list ke dictionary!
Artinya kita mengubah struktur data list menjadi dictionary.
List menyimpan data dalam bentuk urutan elemen, sedangkan Dictionary menyimpan data dalam bentuk pasangan key : value.
List diatas berisi beberapa pasangan data yang nantinya akan dijadikan key dan value pada dictionary.
Cara Mengubah List ke Dictionary yaitu gunakan fungsi dict().

In [ ]:
# Setelah diubah
data = [["Nama","Chatrina"],["NIM","535250096"],["Prodi","Informatika"],["Matakuliah","Numed"]]
hasil = dict(data)
print(hasil)

{'Nama': 'Chatrina', 'NIM': '535250096', 'Prodi': 'Informatika', 'Matakuliah': 'Numed'}
